linters-settings:
  golint:
    min_confidence: 0.8
  govet:
    check_shadowing: true
  goimports:
    local_prefixes: github.com/luccasbarros/the-service

linters:
  enable:
    - errcheck
    - revive
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

run:
  tests: true
  skip-dirs-use-default: true
  skip-dirs:
    - .vscode/