openapi: 3.0.1
info:
  version: 1.0.0
  title: The Service API
  description: The Service API Documentation


components:
  securitySchemes:
    $ref: "./components/SecuritySchemes.yaml"
  responses:
    $ref: "./components/Responses.yaml"
  schemas:
    Users:
      $ref: "./components/schemas/Users.yaml"

paths:
  /auth/users:
    get:
      $ref: "../router/handlers/users/spec.yaml"
  # /auth/login:
  #   post:
  #     $ref: "../routes/auth/login/spec.yaml"