# get
description: Get users
tags:
  - Users

responses:
  200:
    description: Successful response
    content:
      application/json:
        schema:
          type: array
          items:
            $ref: "#/components/schemas/Users"
  400:
    $ref: "#/components/responses/BadRequest"
  401:
    $ref: "#/components/responses/Unauthorized"